"""
Create snippets table.

Revision ID: fbe8289581fc
Revises:
Create Date: 2022-11-06 13:08:43.228312+00:00
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "fbe8289581fc"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "snippets",
        sa.Column("snippet_id", sa.Integer(), nullable=False),
        sa.Column("name", sa.Text(), nullable=False),
        sa.Column("text", sa.Text(), nullable=False),
        sa.PrimaryKeyConstraint("snippet_id", name=op.f("snippets_pk")),
    )
    op.create_index(op.f("snippets_name_ix"), "snippets", ["name"], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("snippets")
    # ### end Alembic commands ###
