"""
Add posts table.

Revision ID: 52fd6cf3df1e
Revises: fbe8289581fc
Create Date: 2022-11-06 15:24:34.818419+00:00
"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "52fd6cf3df1e"
down_revision = "fbe8289581fc"
branch_labels = None
depends_on = None


def upgrade() -> None:
    """Apply this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "posts",
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("forum_post_id", sa.BigInteger(), nullable=False),
        sa.PrimaryKeyConstraint("post_id", name=op.f("posts_pk")),
    )
    op.create_index(op.f("posts_forum_post_id_ix"), "posts", ["forum_post_id"], unique=True)
    op.create_index(op.f("posts_user_id_ix"), "posts", ["user_id"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Revert this migration."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("posts")
    # ### end Alembic commands ###
